language: objective-c
osx_image: mavericks
before_install:
  - gem install xcpretty
script: 
  - xcodebuild -workspace CCHMapClusterController.xcworkspace -scheme 'CCHMapClusterController Example iOS' -sdk iphonesimulator7.0 -configuration Debug -destination 'platform=iOS Simulator,OS=7.0,name=iPhone Retina (4-inch)' test | xcpretty -c; exit ${PIPESTATUS[0]}
  - xcodebuild -workspace CCHMapClusterController.xcworkspace -scheme 'CCHMapClusterController Example OS X' -sdk macosx10.9 -configuration Debug test | xcpretty -c; exit ${PIPESTATUS[0]}
