language: objective-c
osx_image: mavericks
before_install:
  - gem install xcpretty
install: echo
script:
  - export LC_CTYPE=en_US.UTF-8
  - set -o pipefail
  - xcodebuild -workspace CCHMapClusterController.xcworkspace -scheme 'CCHMapClusterController Example iOS' -sdk iphonesimulator -configuration Debug test