language: objective-c
osx_image: mavericks
before_install:
  - gem install xcpretty
script: 
  - set -o pipefail && xcodebuild -workspace CCHMapClusterController.xcworkspace -scheme 'CCHMapClusterController Example iOS' -sdk iphonesimulator7.0 -configuration Debug test | xcpretty -c
  - set -o pipefail && xcodebuild -workspace CCHMapClusterController.xcworkspace -scheme 'CCHMapClusterController Example OS X' -sdk macosx10.9 -configuration Debug test | xcpretty -c
